version: "3.8"

services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_APPLICATION_JSON: >
        {
          "spring": {
            "data": {
              "mongodb": {
                "uri": "mongodb://root:root@ms_mongo_db:27017/productdb?authSource=admin"
              }
            },
            "eureka": {
              "client": {
                "service-url": {
                  "defaultZone": "http://discovery-service:8761/eureka"
                },
                "register-with-eureka": true,
                "fetch-registry": true
              },
              "instance": {
                "prefer-ip-address": true,
                "hostname": "product-service"
              }
            },
            "kafka": {
              "bootstrap-servers": "kafka:9092"
            }
          }
        }
    networks:
      - order-net

networks:
  order-net:
    external: true

