version: "3.8"

services:
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://host.docker.internal:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    networks:
      - order-net

networks:
  order-net:
    driver: bridge
