spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: order-service
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
