spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://mysql:3306/ordersdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none



server:
  port: 8081

eureka:
  client:
    service-url:
      #defaultZone: http://host.docker.internal:8761/eureka
        defaultZone: http://discovery-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
