server:
  port: 8082

spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: product-service

logging:
  level:
    feign: DEBUG
    root: INFO
    org.springframework.security: DEBUG
    com.example.product.product.client: DEBUG
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG

eureka:
  client:
    service-url:
      #defaultZone: http://host.docker.internal:8761/eureka
      defaultZone: http://discovery-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: product-service
