
    version: "3.8"

    services:
      product:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: product-service
        ports:
          - "8082:8082"
        environment:
          SPRING_PROFILES_ACTIVE: docker
          SPRING_CLOUD_CONFIG_URI: http://config-server:8888
          #EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:  http://discovery-service:8761/eureka
          KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        networks:
          - order-net

    networks:
      order-net:
        driver: bridge
        external: true
