
services:
  product:
    build:
      context: .
    container_name: ms_product
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
