version: "3.8"
services:
  discovery-service:
    build:
      context: .
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - order-net
    environment:
      - SERVER_PORT=8761

networks:
  order-net:
    driver: bridge
    external: true