spring:
  application:
    name: product-service

  data:
    mongodb:
      username: root
      password: root
      #host: product-service
      #port: 27017
      #database: product_db
      authentication-database: admin
      uri: mongodb://ms_mongo_db:27017/product_db
      # uri: mongodb://localhost:27017/product_db

  cloud:
    openfeign:
      enabled: true
      circuitbreaker:
        enabled: true
    config:
      import: optional:configserver:http://config-server:8888

  kafka:
    bootstrap-servers: kafka:9092
    admin:
      auto-create: true
      properties:
        replication:
          factor: 1
    producer:
      group-id: product-group
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: com.example.product.dto
    topic.product.created: product-created-topic
    topic.product.updated: product-updated-topic
    topic.product.deleted: product-deleted-topic

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: product-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
networks:
  - order-net
